# Generated by Django 5.2.6 on 2026-03-31 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id_dimension', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dimension', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dimension',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('empresa_activa', models.BooleanField(default=False)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(max_length=50)),
                ('dimension', models.ForeignKey(db_column='dimension_id_dimension', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.dimension')),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'competencia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dimension',
            name='empresa',
            field=models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id_biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.BinaryField(editable=True)),
                ('estado_carga', models.BooleanField(default=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'biblioteca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'escala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NivelJerarquico',
            fields=[
                ('id_nivel_jerarquico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel_jerarquico', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'nivel_jerarquico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
                ('nivel_jerarquico', models.ForeignKey(db_column='nivel_jerarquico_id_nivel_jerarquico', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.niveljerarquico')),
            ],
            options={
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReporteGlobal',
            fields=[
                ('id_reporte_global', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_pdf', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_trabajadores', models.IntegerField(default=0)),
                ('periodo', models.IntegerField(default=2026)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa')),
            ],
            options={
                'db_table': 'reporte_global',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromptGemini',
            fields=[
                ('id_prompt', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_texto', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('respuesta_gemini', models.TextField(blank=True, null=True)),
                ('pdf_generado', models.BooleanField(default=False)),
                ('archivo_pdf', models.BinaryField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa')),
                ('reporte_global', models.ForeignKey(blank=True, db_column='reporte_global_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.reporteglobal')),
            ],
            options={
                'db_table': 'prompt_gemini',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=10)),
                ('es_coordinador', models.BooleanField(db_column='es_coordinador', default=False)),
                ('cargo', models.ForeignKey(db_column='cargo_id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.cargo')),
                ('departamento', models.ForeignKey(db_column='departamento_id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.departamento')),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
                ('id_jefe_directo', models.ForeignKey(blank=True, db_column='id_jefe_directo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subordinados', to='cuestionario.trabajador')),
                ('nivel_jerarquico', models.ForeignKey(db_column='nivel_jerarquico_id_nivel_jerarquico', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.niveljerarquico')),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionJefatura',
            fields=[
                ('id_evaluacion_jefatura', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('fecha_evaluacion', models.DateField()),
                ('momento_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('estado_finalizacion', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('textos_evaluacion_codigo_excel', models.CharField(max_length=10)),
                ('escala', models.ForeignKey(db_column='escala_id_escala', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.escala')),
                ('textos_evaluacion_empresa', models.ForeignKey(db_column='textos_evaluacion_empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluaciones_jefatura_textos', to='cuestionario.empresa')),
                ('evaluador', models.ForeignKey(db_column='evaluador_id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluaciones_como_jefe', to='cuestionario.trabajador')),
                ('trabajador_evaluado', models.ForeignKey(db_column='trabajador_id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluaciones_recibidas', to='cuestionario.trabajador')),
            ],
            options={
                'db_table': 'evaluacion_jefatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('fecha_evaluacion', models.DateField()),
                ('momento_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('estado_finalizacion', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('textos_evaluacion_codigo_excel', models.CharField(max_length=10)),
                ('textos_evaluacion_empresa', models.ForeignKey(db_column='textos_evaluacion_empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autoevaluaciones_textos', to='cuestionario.empresa')),
                ('escala', models.ForeignKey(db_column='escala_id_escala', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.escala')),
                ('trabajador', models.ForeignKey(db_column='trabajador_id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.trabajador')),
            ],
            options={
                'db_table': 'autoevaluacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoEvaluacion',
            fields=[
                ('id_codigo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('textos_evaluacion_codigo_excel', models.CharField(max_length=10)),
                ('competencia', models.ForeignKey(db_column='competencia_id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.competencia')),
                ('dimension', models.ForeignKey(db_column='dimension_id_dimension', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.dimension')),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
                ('textos_evaluacion_empresa', models.ForeignKey(db_column='textos_evaluacion_empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='codigos_evaluacion_textos', to='cuestionario.empresa')),
                ('nivel_jerarquico', models.ForeignKey(db_column='nivel_jerarquico_id_nivel_jerarquico', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.niveljerarquico')),
            ],
            options={
                'db_table': 'codigo_evaluacion',
                'managed': True,
                'unique_together': {('empresa', 'textos_evaluacion_codigo_excel')},
            },
        ),
        migrations.CreateModel(
            name='TextosEvaluacion',
            fields=[
                ('id_textos_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_excel', models.CharField(max_length=10)),
                ('texto', models.TextField()),
                ('competencia', models.ForeignKey(db_column='competencia_id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.competencia')),
                ('dimension', models.ForeignKey(db_column='dimension_id_dimension', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.dimension')),
                ('empresa', models.ForeignKey(db_column='empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.empresa')),
                ('nivel_jerarquico', models.ForeignKey(db_column='nivel_jerarquico_id_nivel_jerarquico', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.niveljerarquico')),
            ],
            options={
                'db_table': 'textos_evaluacion',
                'managed': True,
                'unique_together': {('codigo_excel', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoConsolidado',
            fields=[
                ('id_resultado_consolidado', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_autoev', models.IntegerField()),
                ('puntaje_jefe', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('textos_evaluacion_codigo_excel', models.CharField(max_length=10)),
                ('autoevaluacion', models.ForeignKey(db_column='autoevaluacion_id_autoevaluacion', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.autoevaluacion')),
                ('evaluacion_jefatura', models.ForeignKey(blank=True, db_column='evaluacion_jefatura_id_evaluacion_jefatura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.evaluacionjefatura')),
                ('textos_evaluacion_empresa', models.ForeignKey(db_column='textos_evaluacion_empresa_id_empresa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultados_consolidados_textos', to='cuestionario.empresa')),
                ('trabajador', models.ForeignKey(db_column='trabajador_id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='cuestionario.trabajador')),
            ],
            options={
                'db_table': 'resultado_consolidado',
                'managed': True,
                'unique_together': {('trabajador', 'textos_evaluacion_codigo_excel', 'periodo')},
            },
        ),
    ]
