# Generated by Django 5.2.6 on 2026-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autoevaluacion',
            table='AUTOEVALUACION',
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='CARGO',
        ),
        migrations.AlterModelTable(
            name='competencia',
            table='COMPETENCIA',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='DEPARTAMENTO',
        ),
        migrations.AlterModelTable(
            name='dimension',
            table='DIMENSION',
        ),
        migrations.AlterModelTable(
            name='evaluacionjefatura',
            table='EVALUACION_JEFATURA',
        ),
        migrations.AlterModelTable(
            name='niveljerarquico',
            table='NIVEL_JERARQUICO',
        ),
        migrations.AlterModelTable(
            name='resultadoconsolidado',
            table='RESULTADO_CONSOLIDADO',
        ),
        migrations.AlterModelTable(
            name='textosevaluacion',
            table='TEXTOS_EVALUACION',
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='TRABAJADOR',
        ),
    ]
