# Generated by Django 5.2.6 on 2026-02-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_alter_autoevaluacion_table_alter_cargo_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id_escala', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ESCALA',
                'managed': False,
            },
        ),
    ]
