# Generated by Django 5.2.6 on 2026-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_escala'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionRespuesta',
            fields=[
                ('id_descripcion_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'DESCRIPCION_RESPUESTA',
                'managed': False,
            },
        ),
    ]
