# Generated by Django 5.2.6 on 2026-02-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0004_descripcionrespuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGemini',
            fields=[
                ('id_prompt', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_texto', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('respuesta_gemini', models.TextField(blank=True, null=True)),
                ('pdf_generado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PROMPT_GEMINI',
                'ordering': ['-timestamp'],
            },
        ),
    ]
