# Generated by Django 5.2.6 on 2026-02-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0005_promptgemini'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGlobal',
            fields=[
                ('id_reporte_global', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_pdf', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_trabajadores', models.IntegerField(default=0)),
                ('periodo', models.IntegerField()),
            ],
            options={
                'db_table': 'REPORTE_GLOBAL',
            },
        ),
        migrations.AddField(
            model_name='promptgemini',
            name='archivo_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptgemini',
            name='reporte_global',
            field=models.ForeignKey(blank=True, db_column='REPORTE_GLOBAL_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.reporteglobal'),
        ),
    ]
