# Generated by Django 5.2.6 on 2026-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0006_reporteglobal_promptgemini_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteglobal',
            name='periodo',
            field=models.IntegerField(default=2026),
        ),
    ]
