# Generated by Django 5.2.6 on 2026-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0007_alter_reporteglobal_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id_biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.BinaryField(editable=True)),
                ('estado_carga', models.BooleanField(default=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BIBLIOTECA',
                'managed': False,
            },
        ),
    ]
