# Generated by Django 5.2.6 on 2026-03-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0009_codigoevaluacion_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescripcionRespuesta',
        ),
        migrations.AddField(
            model_name='promptgemini',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='EMPRESA_ID_EMPRESA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa'),
        ),
        migrations.AddField(
            model_name='reporteglobal',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='EMPRESA_ID_EMPRESA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionario.empresa'),
        ),
    ]
