-- =========================
-- Recuerda, antes de iniciar MySql ingresa chcp 65001
-- para no tener problemas con los caracteres especiales
-- CREATE DATABASE sistema_mohala CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE sistema_mohala; SET NAMES 'utf8mb4'; 
-- =========================

SET FOREIGN_KEY_CHECKS = 0;

-- =========================
-- 1. Tabla Escala (NUEVA)
-- =========================
CREATE TABLE ESCALA (
    ID_ESCALA INT NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_ESCALA)
);

-- =========================
-- Tabla Dimension
-- =========================
CREATE TABLE DIMENSION (
    ID_DIMENSION INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DIMENSION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DIMENSION)
);

-- =========================
-- Tabla Departamento
-- =========================
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO)
);

-- =========================
-- Tabla Nivel Jerarquico
-- =========================
CREATE TABLE NIVEL_JERARQUICO (
    ID_NIVEL_JERARQUICO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_NIVEL_JERARQUICO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Cargo
-- =========================
CREATE TABLE CARGO (
    ID_CARGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CARGO VARCHAR(50) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_CARGO),
    CONSTRAINT CARGO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Trabajador (Vinculada con Django Auth)
-- =========================
CREATE TABLE TRABAJADOR (
    ID_TRABAJADOR INT NOT NULL AUTO_INCREMENT,
    RUT VARCHAR(20) NOT NULL,
    ID_JEFE_DIRECTO INT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    GENERO VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    CARGO_ID_CARGO INT NOT NULL,
    DEPARTAMENTO_ID_DEPARTAMENTO INT NOT NULL,
    USER_ID INT UNIQUE NULL, 
    PRIMARY KEY (ID_TRABAJADOR),
    UNIQUE (RUT),
    CONSTRAINT TRABAJADOR_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),
    CONSTRAINT TRABAJADOR_CARGO_FK FOREIGN KEY (CARGO_ID_CARGO)
        REFERENCES CARGO(ID_CARGO),
    CONSTRAINT TRABAJADOR_DEPTO_FK FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT TRABAJADOR_JEFE_FK FOREIGN KEY (ID_JEFE_DIRECTO)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT TRABAJADOR_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES auth_user(id) ON DELETE SET NULL
);

-- =========================
-- Tabla Competencia
-- =========================
CREATE TABLE COMPETENCIA (
    ID_COMPETENCIA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_COMPETENCIA VARCHAR(50) NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    PRIMARY KEY (ID_COMPETENCIA),
    CONSTRAINT COMPETENCIA_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION)
);

-- =========================
-- Tabla Textos Evaluacion
-- =========================
CREATE TABLE TEXTOS_EVALUACION (
    ID_TEXTOS_EVALUACION INT NOT NULL AUTO_INCREMENT,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTO TEXT NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_TEXTOS_EVALUACION),
    UNIQUE (CODIGO_EXCEL),
    CONSTRAINT TEXTO_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION),
    CONSTRAINT TEXTO_COMP_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA)
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
    CONSTRAINT TEXTO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Descripción Respuesta
-- =========================
CREATE TABLE DESCRIPCION_RESPUESTA (
    ID_DESCRIPCION_RESPUESTA INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    ESCALA_ID_ESCALA INT NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_DESCRIPCION_RESPUESTA),
    CONSTRAINT UNQ_DESC_LOGICA UNIQUE (CODIGO_EXCEL, NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO, ESCALA_ID_ESCALA),
    CONSTRAINT DESC_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL) 
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    CONSTRAINT DESC_ESCALA_FK FOREIGN KEY (ESCALA_ID_ESCALA) 
        REFERENCES ESCALA(ID_ESCALA),
    CONSTRAINT DESC_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION) 
        REFERENCES DIMENSION(ID_DIMENSION),
    CONSTRAINT DESC_COMP_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA) 
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
    CONSTRAINT DESC_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO) 
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Autoevaluacion
-- =========================
CREATE TABLE AUTOEVALUACION (
    ID_AUTOEVALUACION INT NOT NULL AUTO_INCREMENT,
    PUNTAJE INT NOT NULL, 
    ESCALA_ID_ESCALA INT NOT NULL, 
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO_FINALIZACION BOOLEAN DEFAULT FALSE NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_AUTOEVALUACION),
    CONSTRAINT AUTO_TRAB_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT AUTO_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    CONSTRAINT AUTO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),
    CONSTRAINT AUTO_ESCALA_FK FOREIGN KEY (ESCALA_ID_ESCALA)
        REFERENCES ESCALA(ID_ESCALA),
    CONSTRAINT UNIQUE_AUTO_TRAB_PREG UNIQUE (TRABAJADOR_ID_TRABAJADOR, CODIGO_EXCEL)
);

-- =========================
-- Tabla Evaluacion Jefatura
-- =========================
CREATE TABLE EVALUACION_JEFATURA (
    ID_EVALUACION_JEFATURA INT NOT NULL AUTO_INCREMENT,
    PUNTAJE INT NOT NULL, 
    ESCALA_ID_ESCALA INT NOT NULL, 
    EVALUADOR_ID_TRABAJADOR INT NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO_FINALIZACION BOOLEAN DEFAULT FALSE NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_EVALUACION_JEFATURA),
    CONSTRAINT JEF_TRAB_EVALUADO_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT JEF_TRAB_EVALUADOR_FK FOREIGN KEY (EVALUADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT JEF_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    CONSTRAINT JEF_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),
    CONSTRAINT JEF_ESCALA_FK FOREIGN KEY (ESCALA_ID_ESCALA)
        REFERENCES ESCALA(ID_ESCALA),
    CONSTRAINT UNIQUE_JEFE_EVAL_PREG UNIQUE (EVALUADOR_ID_TRABAJADOR, TRABAJADOR_ID_TRABAJADOR, CODIGO_EXCEL)
);

-- =========================
-- Tabla Resultado Consolidado
-- =========================
CREATE TABLE RESULTADO_CONSOLIDADO (
    ID_RESULTADO INT NOT NULL AUTO_INCREMENT,
    PUNTAJE_AUTOEV INT NOT NULL, 
    PUNTAJE_JEFE INT NOT NULL,   
    DIFERENCIA INT NOT NULL,     
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PERIODO INT NOT NULL,
    FECHA_CONSOLIDACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT RES_TRAB_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR) 
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT RES_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION) 
        REFERENCES DIMENSION(ID_DIMENSION),
    CONSTRAINT RES_COMP_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA) 
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
    CONSTRAINT RES_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL) 
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    CONSTRAINT RES_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),
    CONSTRAINT UNQ_RES_TRAB_PREG_PERIODO UNIQUE (TRABAJADOR_ID_TRABAJADOR, CODIGO_EXCEL, PERIODO)
);

-- =========================
-- Reporte Global
-- =========================
CREATE TABLE REPORTE_GLOBAL (
    ID_REPORTE_GLOBAL INT AUTO_INCREMENT PRIMARY KEY,
    CONTENIDO_PDF LONGBLOB NOT NULL,
    TIMESTAMP DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    TOTAL_TRABAJADORES INT NOT NULL DEFAULT 0,
    PERIODO INT NOT NULL DEFAULT 2026
);

-- =========================
-- Gemini
-- =========================
CREATE TABLE PROMPT_GEMINI (
    ID_PROMPT INT AUTO_INCREMENT PRIMARY KEY,
    PROMPT_TEXTO TEXT NOT NULL,
    TIMESTAMP DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    RESPUESTA_GEMINI TEXT NULL,
    PDF_GENERADO TINYINT(1) NOT NULL DEFAULT 0,
    ARCHIVO_PDF LONGBLOB NULL,
    REPORTE_GLOBAL_ID INT NULL,
    CONSTRAINT FK_PROMPT_REPORTE FOREIGN KEY (REPORTE_GLOBAL_ID) 
        REFERENCES REPORTE_GLOBAL(ID_REPORTE_GLOBAL) ON DELETE SET NULL
);

-- =========================
-- Biblioteca
-- =========================
CREATE TABLE BIBLIOTECA (
    ID_BIBLIOTECA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ARCHIVO LONGBLOB NOT NULL,
    ESTADO_CARGA BOOLEAN NOT NULL DEFAULT FALSE,
    FECHA_CARGA TIMESTAMP NOT NULL
);

-- Forzar lectura correcta
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;