-- =========================
-- Recuerda, antes de iniciar MySql ingresa chcp 65001
-- para no tener problemas con los caracteres especiales
-- CREATE DATABASE sistema_mohala CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE sistema_mohala; SET NAMES 'utf8mb4'; 
-- =========================

SET FOREIGN_KEY_CHECKS = 0;

-- =========================
-- Biblioteca
-- =========================
CREATE TABLE BIBLIOTECA (
    ID_BIBLIOTECA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    ARCHIVO LONGBLOB NOT NULL,
    ESTADO_CARGA BOOLEAN NOT NULL DEFAULT FALSE,
    FECHA_CARGA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- Reporte Global
-- =========================
CREATE TABLE REPORTE_GLOBAL (
    ID_REPORTE_GLOBAL INT AUTO_INCREMENT PRIMARY KEY,
    CONTENIDO_PDF LONGBLOB NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOTAL_TRABAJADORES INT NOT NULL DEFAULT 0,
    PERIODO INT NOT NULL DEFAULT 2026
);

-- =========================
--  Prompt Gemini
-- =========================
CREATE TABLE PROMPT_GEMINI (
    ID_PROMPT INT AUTO_INCREMENT PRIMARY KEY,
    PROMPT_TEXTO TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RESPUESTA_GEMINI TEXT NULL,
    PDF_GENERADO TINYINT(1) NOT NULL DEFAULT 0,
    ARCHIVO_PDF LONGBLOB NULL,
    REPORTE_GLOBAL_ID INT NULL,

    CONSTRAINT FK_PROMPT_REPORTE FOREIGN KEY (REPORTE_GLOBAL_ID) 
        REFERENCES REPORTE_GLOBAL(ID_REPORTE_GLOBAL) ON DELETE SET NULL
);

-- =========================
-- Tabla Empresa
-- =========================
CREATE TABLE EMPRESA (
    ID_EMPRESA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_EMPRESA VARCHAR(100) NOT NULL,
    RUT_EMPRESA VARCHAR(20) NOT NULL UNIQUE,
    EMPRESA_ACTIVA BOOLEAN NOT NULL DEFAULT FALSE,
    REGISTRADA_EN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_EMPRESA)
);

-- =========================
-- Tabla Departamento
-- =========================
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO),

    CONSTRAINT DEPARTAMENTO_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- =========================
-- Tabla Nivel Jerarquico
-- =========================
CREATE TABLE NIVEL_JERARQUICO (
    ID_NIVEL_JERARQUICO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_NIVEL_JERARQUICO VARCHAR(50) NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_NIVEL_JERARQUICO),

    CONSTRAINT NIVEL_JERARQUICO_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- =========================
-- Tabla Escala
-- =========================
CREATE TABLE ESCALA (
    ID_ESCALA INT NOT NULL AUTO_INCREMENT,
    VALOR INT NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_ESCALA),

    CONSTRAINT ESCALA_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- =========================
-- Tabla Dimension
-- =========================
CREATE TABLE DIMENSION (
    ID_DIMENSION INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DIMENSION VARCHAR(50) NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_DIMENSION),

    CONSTRAINT DIMENSION_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- =========================
-- Tabla Competencia
-- =========================
CREATE TABLE COMPETENCIA (
    ID_COMPETENCIA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_COMPETENCIA VARCHAR(50) NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_COMPETENCIA),

    CONSTRAINT COMPETENCIA_DIMENSION_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION),

    CONSTRAINT COMPETENCIA_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- =========================
-- Tabla Cargo
-- =========================
CREATE TABLE CARGO (
    ID_CARGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CARGO VARCHAR(50) NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_CARGO),

    CONSTRAINT CARGO_NIVEL_JERARQUICO_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),

    CONSTRAINT CARGO_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA)
);

-- =========================
-- Tabla Textos Evaluación
-- =========================
CREATE TABLE TEXTOS_EVALUACION (
    ID_TEXTOS_EVALUACION INT NOT NULL AUTO_INCREMENT,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTO TEXT NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_TEXTOS_EVALUACION),
    
    UNIQUE (CODIGO_EXCEL, EMPRESA_ID_EMPRESA),

    CONSTRAINT TEXTOS_EVALUACION_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA),

    CONSTRAINT TEXTOS_EVALUACION_DIMENSION_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION),

    CONSTRAINT TEXTOS_EVALUACION_COMPETENCIA_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA)
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
        
    CONSTRAINT TEXTOS_EVALUACION_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Código Evaluación
-- =========================
CREATE TABLE CODIGO_EVALUACION (
    ID_CODIGO_EVALUACION INT NOT NULL AUTO_INCREMENT,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    TEXTOS_EVALUACION_CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_CODIGO_EVALUACION),

    CONSTRAINT CODIGO_EVALUACION_UC1 UNIQUE (EMPRESA_ID_EMPRESA, TEXTOS_EVALUACION_CODIGO_EXCEL),

    CONSTRAINT CODIGO_EVALUACION_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA),

    CONSTRAINT CODIGO_EVALUACION_DIMENSION_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION),

    CONSTRAINT CODIGO_EVALUACION_COMPETENCIA_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA)
        REFERENCES COMPETENCIA(ID_COMPETENCIA),

    CONSTRAINT CODIGO_EVALUACION_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),

    CONSTRAINT CODIGO_EVALUACION_TEXTOS_FK FOREIGN KEY (TEXTOS_EVALUACION_CODIGO_EXCEL, TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL, EMPRESA_ID_EMPRESA)
);

-- =========================
-- Tabla Descripción Respuesta
-- =========================
CREATE TABLE DESCRIPCION_RESPUESTA (
    ID_DESCRIPCION_RESPUESTA INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    TEXTOS_EVALUACION_CODIGO_EXCEL VARCHAR(10) NOT NULL,
    ESCALA_ID_ESCALA INT NOT NULL,
    PRIMARY KEY (ID_DESCRIPCION_RESPUESTA),

    CONSTRAINT DESCRIPCION_RESPUESTA_UC1 UNIQUE (EMPRESA_ID_EMPRESA, TEXTOS_EVALUACION_CODIGO_EXCEL, ESCALA_ID_ESCALA),

    CONSTRAINT DESCRIPCION_RESPUESTA_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA) 
        REFERENCES EMPRESA(ID_EMPRESA),

    CONSTRAINT DESCRIPCION_RESPUESTA_CODIGO_EVALUACION_FK FOREIGN KEY (EMPRESA_ID_EMPRESA, TEXTOS_EVALUACION_CODIGO_EXCEL)
        REFERENCES CODIGO_EVALUACION(EMPRESA_ID_EMPRESA, TEXTOS_EVALUACION_CODIGO_EXCEL),

    CONSTRAINT DESCRIPCION_RESPUESTA_ESCALA_FK FOREIGN KEY (ESCALA_ID_ESCALA) 
        REFERENCES ESCALA(ID_ESCALA)
);

-- =========================
-- Tabla Trabajador (Vinculada con Django Auth)
-- =========================
CREATE TABLE TRABAJADOR (
    ID_TRABAJADOR INT NOT NULL AUTO_INCREMENT,
    RUT VARCHAR(20) NOT NULL UNIQUE,
    ID_JEFE_DIRECTO INT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    GENERO VARCHAR(10) NOT NULL,
    EMPRESA_ID_EMPRESA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    CARGO_ID_CARGO INT NOT NULL,
    DEPARTAMENTO_ID_DEPARTAMENTO INT NOT NULL,
    USER_ID INT UNIQUE NULL, 
    PRIMARY KEY (ID_TRABAJADOR),
    
    CONSTRAINT TRABAJADOR_EMPRESA_FK FOREIGN KEY (EMPRESA_ID_EMPRESA)
        REFERENCES EMPRESA(ID_EMPRESA),

    CONSTRAINT TRABAJADOR_NIVEL_JERARQUICO_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),

    CONSTRAINT TRABAJADOR_CARGO_FK FOREIGN KEY (CARGO_ID_CARGO)
        REFERENCES CARGO(ID_CARGO),

    CONSTRAINT TRABAJADOR_DEPARTAMENTO_FK FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),

    CONSTRAINT TRABAJADOR_JEFE_FK FOREIGN KEY (ID_JEFE_DIRECTO)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),

    CONSTRAINT TRABAJADOR_USER_FK FOREIGN KEY (USER_ID)
        REFERENCES auth_user(id) ON DELETE SET NULL
);

-- =========================
-- Tabla Autoevaluación
-- =========================
CREATE TABLE AUTOEVALUACION (
    ID_AUTOEVALUACION INT NOT NULL AUTO_INCREMENT,
    PUNTAJE INT NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO_FINALIZACION BOOLEAN NOT NULL DEFAULT FALSE,
    COMENTARIO TEXT NULL,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    TEXTOS_EVALUACION_CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA INT NOT NULL,
    ESCALA_ID_ESCALA INT NOT NULL,
    PRIMARY KEY (ID_AUTOEVALUACION),

    CONSTRAINT AUTOEVALUACION_TRABAJADOR_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),

    CONSTRAINT AUTOEVALUACION_TEXTOS_EVALUACION_FK FOREIGN KEY (TEXTOS_EVALUACION_CODIGO_EXCEL, TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL, EMPRESA_ID_EMPRESA),

    CONSTRAINT AUTOEVALUACION_ESCALA_FK FOREIGN KEY (ESCALA_ID_ESCALA)
        REFERENCES ESCALA(ID_ESCALA)
);

-- =========================
-- Tabla Evaluación Jefatura
-- =========================
CREATE TABLE EVALUACION_JEFATURA (
    ID_EVALUACION_JEFATURA INT NOT NULL AUTO_INCREMENT,
    PUNTAJE INT NOT NULL,
    EVALUADOR_ID_TRABAJADOR INT NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO_FINALIZACION BOOLEAN NOT NULL DEFAULT FALSE,
    COMENTARIO TEXT NULL,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    TEXTOS_EVALUACION_CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA INT NOT NULL,
    ESCALA_ID_ESCALA INT NOT NULL,
    PRIMARY KEY (ID_EVALUACION_JEFATURA),

    CONSTRAINT EVALUACION_JEFATURA_TRABAJADOR_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),

    CONSTRAINT EVALUACION_JEFATURA_EVALUADOR_FK FOREIGN KEY (EVALUADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),

    CONSTRAINT EVALUACION_JEFATURA_TEXTOS_EVALUACION_FK FOREIGN KEY (TEXTOS_EVALUACION_CODIGO_EXCEL, TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL, EMPRESA_ID_EMPRESA),

    CONSTRAINT EVALUACION_JEFATURA_ESCALA_FK FOREIGN KEY (ESCALA_ID_ESCALA)
        REFERENCES ESCALA(ID_ESCALA)
);


-- =========================
-- Tabla Resultado Consolidado
-- =========================
CREATE TABLE RESULTADO_CONSOLIDADO (
    ID_RESULTADO_CONSOLIDADO INT NOT NULL AUTO_INCREMENT,
    PUNTAJE_AUTOEV INT NOT NULL,
    PUNTAJE_JEFE INT NOT NULL,
    DIFERENCIA INT NOT NULL,
    PERIODO INT NOT NULL,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    AUTOEVALUACION_ID_AUTOEVALUACION INT NOT NULL,
    EVALUACION_JEFATURA_ID_EVALUACION_JEFATURA INT NOT NULL,
    TEXTOS_EVALUACION_CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA INT NOT NULL,
    PRIMARY KEY (ID_RESULTADO_CONSOLIDADO),

    CONSTRAINT RESULTADO_CONSOLIDADO_TRABAJADOR_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),

    CONSTRAINT RESULTADO_CONSOLIDADO_AUTOEVALUACION_FK FOREIGN KEY (AUTOEVALUACION_ID_AUTOEVALUACION)
        REFERENCES AUTOEVALUACION(ID_AUTOEVALUACION),

    CONSTRAINT RESULTADO_CONSOLIDADO_EVALUACION_JEFATURA_FK FOREIGN KEY (EVALUACION_JEFATURA_ID_EVALUACION_JEFATURA)
        REFERENCES EVALUACION_JEFATURA(ID_EVALUACION_JEFATURA),

    CONSTRAINT RESULTADO_CONSOLIDADO_TEXTOS_EVALUACION_FK FOREIGN KEY (TEXTOS_EVALUACION_CODIGO_EXCEL, TEXTOS_EVALUACION_EMPRESA_ID_EMPRESA)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL, EMPRESA_ID_EMPRESA)
);

-- Forzar lectura correcta
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;